# Generated by Django 5.1.3 on 2024-12-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0002_order_city_order_country_order_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(default='Default city', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(default='Default country', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(default='Default postal_code', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='street_address',
            field=models.CharField(default='Dafault', max_length=255),
            preserve_default=False,
        ),
    ]
