# Generated by Django 5.1.3 on 2024-12-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0003_alter_order_city_alter_order_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='API_token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
            ],
        ),
    ]
